name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - Production
  pull_request:
    branches:
      - Production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. Restore
    - name: Restore dependencies
      run: dotnet restore ServicePro.API/ServicePro.API.csproj

    # 4. Build
    - name: Build
      run: dotnet build ServicePro.API/ServicePro.API.csproj --configuration Release --no-restore

    # 5. Test
    - name: Test
      run: dotnet test ServicePro.API/ServicePro.API.csproj --no-build --verbosity normal

    # 6. Publish
    - name: Publish
      run: dotnet publish ServicePro.API/ServicePro.API.csproj -c Release -o publish

    # 7. Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-build
        path: publish

    # 8. Install SQLCMD
    - name: Install SQLCMD
      run: |
        sudo apt-get update
        sudo apt-get install -y curl apt-transport-https
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

    # 9. Run DB Scripts Safely
    - name: Run DB Scripts Safely
      run: |
        set -e

        echo "Listing SQL files..."
        ls -l database/scripts || echo "Folder not found"

        found=false

        for file in database/scripts/*.sql; do
          if [ -f "$file" ]; then
            found=true
            echo "Running $file"
            /opt/mssql-tools/bin/sqlcmd -b \
              -S $DB_SERVER \
              -U $DB_USER \
              -P $DB_PASS \
              -d $DB_NAME \
              -i "$file"
          fi
        done

        if [ "$found" = false ]; then
          echo "No SQL files found. Skipping DB step."
        fi
      env:
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
