name: Manual DB Sync (Extract + Save)

on:
  workflow_dispatch:

jobs:
  sync-db:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install SQLPackage
      run: |
        choco install sqlpackage -y

    - name: Generate SQL Script from DB
      run: |
        sqlpackage /Action:Script ^
        /SourceConnectionString:"${{ secrets.DB_CONNECTION_STRING }}" ^
        /TargetFile:database/scripts/output.sql

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto DB Sync - Updated SQL Script" || echo "No changes"
        git push
